config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  resources :events, only: [:new, :create, :show, :index]
  resources :attendances, only: [:new, :create, :show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'events#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :attendee, class_name: 'User'
  belongs_to :attended_event, class_name: 'Event'
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User'
  has_many :attendances, foreign_key: :attended_event_id
  has_many :attendees, through: :attendances

  validates :title, presence: true, length: { minimum: 5 }
  validates :date, presence: true
  validates :description, presence: true, length: { minimum: 5 }
  validates :location, presence: true, length: { minimum: 5 }

  scope :past, -> { where('date < ?', DateTime.current.localtime) }
  scope :upcoming, -> { where('date > ?', DateTime.current.localtime) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :created_events, foreign_key: :creator_id, class_name: 'Event'
  has_many :attendances, foreign_key: :attendee_id
  has_many :attended_events, through: :attendances

  validates :name, presence: true, length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  def create
    @attendance = Attendance.new(attended_event_id: params[:attended_event_id], attendee_id: params[:attendee_id])

    respond_to do |format|
      if @attendance.save
        format.html do
          redirect_to event_path(@attendance.attended_event_id), notice: 'You registered succesfully to this event.'
        end
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_user, only: %i[new create]

  def index
    @events = Event.all
  end

  # GET /events/1
  def show
    @event = Event.find(params[:id])
    @attendees = @event.attendees
  end

  # GET /users/new
  def new
    @event = Event.new
  end

  # POST /users
  def create
    @event = @set_user.created_events.build(event_params)

    respond_to do |format|
      if @event.save
        @attendance = Attendance.new(attended_event_id: @event.id, attendee_id: @event.creator_id)
        @attendance.save
        format.html { redirect_to @event, notice: 'The event was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @set_user ||= session[:current_user_id] && User.find_by(id: session[:current_user_id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.require(:event).permit(:title, :description, :date, :location, :creator_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if User.exists?(name: params[:name])
      user = User.where(name: params[:name])
      session[:current_user_id] = user[0].id
      redirect_to root_url
    else
      redirect_to new_session_path
    end
  end

  def destroy
    session.delete(:current_user_id)
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show]

  # GET /users/1 or /users/1.json
  def show
    if set_user
      @user = @set_user
    else
      redirect_to new_user_path
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:current_user_id] = @user.id
        format.html { redirect_to @user, notice: 'User was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @set_user ||= session[:current_user_id] && User.find_by(id: session[:current_user_id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user
    User.find_by(id: session[:current_user_id]) if session[:current_user_id]
  end

  def user_created_events
    @user.created_events.all
  end
end

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="actions pink-button">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/index.html.erb
<div class="event-index">
  <div class="flex">
    <h2 class="title">Previous Events</h2>
      <% @events.past.each do | event | %>
      <div class="pink-border">
        <h2 class="title-links"><%= link_to(event.title, event) %></h2>
        <p><%= event.description %></p>
        <div>
          <p>Date: <%= event.date %></p>
          <p>Location: <%= event.location %></p>
        </div>
      </div>
    <% end %>
  </div>
  <div class="flex">
    <h2 class="title">Upcoming Events</h2>
    <% @events.upcoming.each do | event | %>
      <div class="pink-border">
        <h2 class="title-links"><%= link_to(event.title, event) %></h2>
        <p><%= event.description %></p>
        <div>
          <p>Date: <%= event.date %></p>
          <p>Location: <%= event.location %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/events/new.html.erb
<div class="flex new-event">
  <h2 class="title">New Event</h2>
  <%= render 'form', event: @event %>
</div>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>
<div class="flex-start full-view">
  <div class="flex">
    <h2 class="title">Event:</h2>
    <span class="name"><%= @event.title %></span>
  </div>
  <div class="flex">
    <h2 class="title">Created by: </h2>
    <span class="name"><%= @event.creator.name %></span>
  </div>
  <div class="event-info flex">
    <div class="flex">
      <h3 class="title">Description:</h3>
      <span class="info"><%= @event.description %></span>
    </div>
    <div class="flex-row">
      <div class="flex">
        <h3 class="title">Date:</h3>
        <span class="info"><%= @event.date %></span>
      </div>
      <div class="flex">
          <h3 class="title">Location:</h3>
          <span class="info"><%= @event.location %></span>
      </div>
    </div>
    <div class="flex">
      <h3 class="title">Attendees:</h3>
      <% @attendees.each do | attendee | %>
      <span class="info"><%= attendee.name %></span>
      <br>
      <% end %>
    </div>
  </div>
    <% if @event.date > DateTime.current.localtime && current_user && @attendees.exists?(current_user.id) != true %>
      <span class="pink-button"><%= link_to('Register', attendances_path(attendee_id: current_user.id, attended_event_id: @event.id), method: :post) %></span>
    <% end %>
  <div class="m-t">
    <span class="title-links"><%= link_to 'Back', root_path %></span>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Private Events</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <div class="navbar">
    <span class="logo"><%= link_to 'Events Nation', root_path %></span>

    <div>
      <span class="user-links"><%= link_to('Create an Event', new_event_path) if current_user %></span>
      <span class="user-links"><%= link_to('Log In', new_session_path) unless current_user %></span>
      <span class="user-links"><%= link_to(current_user.name, user_path(current_user.id)) if current_user %></span>
      <span class="user-links"><%= link_to('Log Out', session_path(current_user.id), method: :delete) if current_user %></span>
      <span class="user-links"><%= link_to('Sign Up', new_user_path) unless current_user %></span>
    </div>
  </div>
  <%= yield %>
</body>

</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="flex">
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

    <div class="actions pink-button">
      <%= form.submit 'Sign up' %>
    </div>
  </div>
<% end %>

app/views/users/new.html.erb
<div class="flex full-view">
  <h1 class="title">Sign Up</h1>

  <%= render 'form', user: @user %>

  <span class="title-links"><%= link_to 'Back', events_path %></span>
</div>

app/views/users/show.html.erb
<div class="flex show-user">
  <p id="notice"><%= notice %></p>
  <div class="flex-row">
    <h2 class="title name-title">Name:</h2>
    <span class="name"><%= @user.name %></span>
  </div>
  <div class="flex-row">
    <div class="flex-start column">
      <h2 class="title top">Hosting</h2>
      <% user_created_events.each do |event| %>
        <div>
          <h3>Title:</h3>
          <%= event.title %>

          <div class="event-info">
            <div>
              <h3>Date:</h3>
              <%= event.date %>
            </div>
            <div>
              <h3>Location:</h3>
              <%= event.location %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="flex-start column">
      <h2 class="title top">Previous Events</h2>
      <% @user.attended_events.past.each do | event | %>
        <%= event.title %>

        <div class="event-info">
          <div>
            <h3>Date:</h3>
            <%= event.date %>
          </div>
          <div>
            <h3>Location:</h3>
            <%= event.location %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="flex-start column">
      <h2 class="title top">Upcoming Events</h2>
      <% @user.attended_events.upcoming.each do | event | %>
        <%= event.title %>

        <div class="event-info">
          <div>
            <h3>Date:</h3>
            <%= event.date %>
          </div>
          <div>
            <h3>Location:</h3>
            <%= event.location %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <div class="title-links">
    <%= link_to 'Back', events_path %>
  </div>
</div>